/// <reference types="cypress" />

describe('update a project', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.get('[name="projectName"]').type('A')
    cy.get('[name="pattern"]').type('very')
    cy.get('[name="size"]').type('new')
    cy.get('[name="nextStep"]').type('project')
    cy.get('button').click()
  })

  it('should update every entry of a project', () => {
    cy.get('li').children('div').children('button').click()
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="projectName"]')
      .clear()
      .type('Summer dress')
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="pattern"]')
      .clear()
      .type('Burda Modell 101')
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="size"]')
      .clear()
      .type('36')
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="nextStep"]')
      .clear()
      .type('sew')
    cy.get('li').children('form').children('button').click()
    cy.get('li')
      .children('div')
      .should((p) => {
        expect(p).to.contain('Summer dress')
        expect(p).to.contain('Burda Modell 101')
        expect(p).to.contain('36')
        expect(p).to.contain('sew')
      })
  })

  it('should fail with no project name input', () => {
    cy.get('li').children('div').children('button').click()
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="projectName"]')
      .clear()
    cy.get('li').children('form').children('button').click()
    cy.get('li').should((div) => {
      expect(div).to.contain('Better keep a project name!')
    })
  })

  it('should fail with no next step input', () => {
    cy.get('li').children('div').children('button').click()
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="nextStep"]')
      .clear()
    cy.get('li').children('form').children('button').click()
    cy.get('li').should((div) => {
      expect(div).to.contain('Keep track of the next step!')
    })
  })

  it('should fail with too long inputs', () => {
    cy.get('li').children('div').children('button').click()
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="projectName"]')
      .type('Summer dress with sleevesSummer dress with sleeves')
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="pattern"]')
      .type(
        'PinterestPinterestPinterestPinterestPinterestPinterestPinterestPinterestPinterest'
      )
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="size"]')
      .type('3838383838383838383838383838383838383838383838383838')
    cy.get('li')
      .children('form')
      .children('label')
      .children('[name="nextStep"]')
      .type(
        'cut fabric and lining, buy button, zipper and tapecut fabric and lining, buy button, zipper and tape'
      )
    cy.get('li').children('form').children('button').click()
    cy.get('li').should((div) => {
      expect(div).to.contain('Make it short and sweet!')
      expect(div).to.contain('The text is too long...')
      expect(div).to.contain("Don't make it too long")
    })
  })
})
